name: main

on:
  - push
  - pull_request

jobs:
  main:
    name: 'Test and Lint'
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '24'

      - run: npm install

      - run: npm test

      - run: npm run lint